[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn consultantt.wsgi:application --bind 0.0.0.0:${PORT:-8080} --workers 2 --threads 4 --timeout 60 --log-level debug --access-logfile - --error-logfile -"