[phases.build]
cmds = [
  "pip install -r requirements.txt",
  "python manage.py collectstatic --noinput",
  "python manage.py migrate --noinput"
]

[start]
cmd = "gunicorn consultantt.wsgi --workers 2 --threads 4 --timeout 60 --log-file -"
