# Generated by Django 4.2.28 on 2026-02-28 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл документа')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='previews/', verbose_name='Превью')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email покупателя')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('waiting_payment', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('sent', 'Отправлен'), ('cancelled', 'Отменён')], default='created', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('kaspi', 'Kaspi'), ('bank', 'Банк')], default='kaspi', max_length=10, verbose_name='Способ оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
